### ISSUE TITLE
pathToFile is ignored in config

### ISSUE THREAD

**Issue by moescs** [Awesome-T/arb_gen#2]
The source file is always hardcoded to be arb.gen/content.json no matter what pathToFile says

1. Edit config.json to have pathToFile: "foo/bar.arb"
2. Run arb_gen
3. See error that content.json does not exist

**Expected Behavior**
bar.arb in directory foo should be used instead of content.json in directory arb.gen

**Comment by Awesome-T** [comment]
>The source file is always hardcoded to be arb.gen/content.json no matter what pathToFile says

Thank you for reaching out to me.
I am happy to inform you that the bug has been [resolved](https://github.com/Awesome-T/arb_gen/blob/a7aeffe76ff57a99c6697867b88443e9fa238575/src/util/config.dart#L50). You are doing great with your coding!
